/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Begin */

#ifndef _Included_Begin
#define _Included_Begin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Begin
 * Method:    processAccount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Begin_processAccount
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
